name: climaax_fire

channels:
    - conda-forge

dependencies:
    - gdal=3.9.1
    - geopandas=1.0.1
    - ipykernel=6.29.5
    - jupyterlab-myst=2.4.2
    - jupyterlab=4.2.3
    - matplotlib=3.8.4
    - notebook=7.2.1
    - numpy=1.26.4
    - openpyxl=3.1.4
    - p7zip=16.02
    - pandas=2.2.2
    - pip
    - pooch=1.8.2
    - python=3.11
    - rasterio=1.3.10
    - scikit-learn
    - scipy=1.14.0
    - tqdm=4.66.4
    - xlrd=2.0.1

