name: climaax_fire

channels:
    - conda-forge

dependencies:
    - basemap=1.4.1
    - bottleneck=1.4.0
    - cartopy=0.23.0
    - cdsapi=0.7.0
    - dask=2024.7.0
    - gdal=3.9.1
    - geopandas=1.0.1
    - ipykernel=6.29.5
    - jupyterlab-myst=2.4.2
    - jupyterlab=4.2.3
    - matplotlib=3.8.4
    - mplleaflet=0.0.5
    - netcdf4=1.7.1
    - notebook=7.2.1
    - numpy=1.26.4
    - openpyxl=3.1.4
    - p7zip=16.02
    - pandas=2.2.2
    - pip
    - pooch=1.8.2
    - pyproj=3.6.1
    - python=3.11
    - rasterio=1.3.10
    - rioxarray=0.15.7
    - scikit-learn=1.5.1
    - scipy=1.14.0
    - tqdm=4.66.4
    - xarray=2024.6.0
    - xlrd=2.0.1
    - pip:
        - paretoset==1.2.4
