name: climaax_fire

channels:
    - conda-forge

dependencies:
    - affine=2.4.0
    - bokeh=3.5.0
    - bottleneck=1.4.0
    - cartopy=0.23.0
    - cdsapi=0.7.5
    - dask=2024.7.0
    - gdal=3.9.1
    - geopandas=1.0.1
    - ipykernel=6.29.5
    - jupyterlab-myst=2.4.2
    - jupyterlab=4.2.7
    - matplotlib=3.8.4
    - netcdf4=1.7.1
    - notebook=7.2.2
    - numba=0.60.0
    - numpy=1.26.4
    - openpyxl=3.1.4
    - pandas=2.2.2
    - pip
    - pooch=1.8.2
    - pyproj=3.6.1
    - python=3.12
    - rasterio=1.3.10
    - rioxarray=0.15.7
    - scikit-learn=1.5.1
    - scipy=1.15.2
    - seaborn=0.13.2
    - tqdm=4.66.4
    - xarray=2024.6.0
    - xlrd=2.0.1
    - zarr=2.18.2
    - pip:
        - "git+https://github.com/ecmwf/earthkit-meteo.git@feature/extreme-values"
        - earthkit-plots==0.2.8
        - gisco-geodata==0.1.2
        - git+https://github.com/tommyod/paretoset@5d8f3a739eeb38fb0b63340840353ad99845a5f0
